;ws	 = $60

z80_f:	.res 1
z80_a:	.res 1
z80_af	= z80_f

z80_c:	.res 1
z80_b:	.res 1
z80_bc	= z80_c

z80_e:	.res 1
z80_d:	.res 1
z80_de	= z80_e

z80_l:	.res 1
z80_h:	.res 1
z80_hl	= z80_l

z80_x:	.res 1
z80_i:	.res 1
z80_ix	= z80_x

z80_iy:	.res 2

z80_fp:	.res 1
z80_ap:	.res 1

z80_cp:	.res 1
z80_bp:	.res 1
z80_bcp	= z80_cp

z80_ep:	.res 1
z80_dp:	.res 1
z80_dep	= z80_ep

z80_lp:	.res 1
z80_hp:	.res 1
z80_hlp	= z80_lp

z80_sp:	.res 2

z80_reg0:	.res 1
z80_reg1:	.res 1
z80_reg2:	.res 1
z80_reg3:	.res 1

z80_r:	 .res 1

